name: vgo
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.1
  flutter_signin_button: ^1.1.0
  video_player: ^1.0.0
  image_picker: ^0.6.7+12
  firebase_storage: ^5.0.1
  image_cropper: ^1.3.1
  carousel_slider: ^2.3.1
  floating_search_bar: ^0.3.0
  path_provider: ^1.6.24
  path: ^1.7.0
  permission_handler: ^5.0.1+1
  camera: ^0.5.8+11
  flutter_swiper: ^1.1.6
  inview_notifier_list: ^1.0.0
  visibility_detector: ^0.1.5
  # file_picker: ^2.0.7
  # video_player: ^0.11.0
  # inview_notifier_list: ^1.0.0
  # video_player_platform_interface: ^2.1.1
  # scrollable_positioned_list: ^0.1.8
  # carousel_slider: ^2.3.1
  # floating_search_bar: ^0.3.0
  # stacked_services: 0.5.4+3
  # intl: ^0.16.1
  # get_it: ^5.0.0
  # tabbar: ^0.1.1
  # google_fonts: ^1.1.0
  # stacked: ^1.7.6
  # marquee: ^1.6.1
  # image: ^2.1.18
  # image_picker: ^0.6.7+12
  # timeago: ^2.0.27
  # flutter_swiper: ^1.1.6
  # path_provider: ^1.6.18
  # cached_network_image: ^2.3.2+1
  firebase_core : ^0.5.0
  # video_compress: ^2.1.0
  firebase_auth: ^0.18.1+1
  # video_trimmer: ^0.3.2
  cloud_firestore: ^0.14.0+2
  # esys_flutter_share: ^1.0.2
  # flutter_launcher_icons: ^0.8.0
  # flutter_signin_button: ^1.1.0
  # outline_material_icons: ^0.1.1
  # simple_timer: ^1.0.1
  # floating_bottom_navigation_bar: ^1.3.0
  # responsive_builder: ^0.3.0
  # font_awesome_flutter: ^8.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"    

flutter:

  uses-material-design: true
  assets:
    - images/